#  Copyright © 2026 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# AUTO-GENERATED BY `python -m evo.compute._stubgen generate`. DO NOT EDIT.
#
# Catalogue snapshot: GET /compute/orgs/{org_id}/tasks?details=true
# Captured: 2026-09-21
#
# The runtime is always live, so tasks published after the snapshot still run --
# they are simply not statically known until the snapshot is refreshed. Use
# `ComputeClient.arun(topic, task, parameters)`, or `SyncComputeClient.run(...)`,
# to reach them.

from ..._facade_types import (
    _GeostatisticsBreakTiesHandle,
    _GeostatisticsConditionalTurningBandsHandle,
    _GeostatisticsConSimHandle,
    _GeostatisticsContinuousDistributionHandle,
    _GeostatisticsDeclusteringHandle,
    _GeostatisticsExperimentalVariogramHandle,
    _GeostatisticsIDWHandle,
    _GeostatisticsKNNHandle,
    _GeostatisticsKrigingHandle,
    _GeostatisticsLocationWiseHandle,
    _GeostatisticsLossCalculationHandle,
    _GeostatisticsNormalScoreHandle,
    _GeostatisticsProfitCalculationHandle,
    _GeostatisticsSimulationReportHandle,
)
from .break_ties import BreakTiesResult as BreakTiesResult
from .conditional_turning_bands import ConditionalTurningBandsResult as ConditionalTurningBandsResult
from .declustering import DeclusteringResult as DeclusteringResult
from .idw import IDWResult as IDWResult
from .knn import KNNResult as KNNResult
from .kriging import BlockDiscretisation as BlockDiscretisation
from .kriging import Filter as Filter
from .kriging import KrigingDiagnostics as KrigingDiagnostics
from .kriging import KrigingResult as KrigingResult
from .location_wise import LocationWiseResult as LocationWiseResult

BreakTies: _GeostatisticsBreakTiesHandle
ConSim: _GeostatisticsConSimHandle
ConditionalTurningBands: _GeostatisticsConditionalTurningBandsHandle
ContinuousDistribution: _GeostatisticsContinuousDistributionHandle
Declustering: _GeostatisticsDeclusteringHandle
ExperimentalVariogram: _GeostatisticsExperimentalVariogramHandle
IDW: _GeostatisticsIDWHandle
KNN: _GeostatisticsKNNHandle
Kriging: _GeostatisticsKrigingHandle
LocationWise: _GeostatisticsLocationWiseHandle
LossCalculation: _GeostatisticsLossCalculationHandle
NormalScore: _GeostatisticsNormalScoreHandle
ProfitCalculation: _GeostatisticsProfitCalculationHandle
SimulationReport: _GeostatisticsSimulationReportHandle

__all__ = [
    "IDW",
    "KNN",
    "BlockDiscretisation",
    "BreakTies",
    "BreakTiesResult",
    "ConSim",
    "ConditionalTurningBands",
    "ConditionalTurningBandsResult",
    "ContinuousDistribution",
    "Declustering",
    "DeclusteringResult",
    "ExperimentalVariogram",
    "Filter",
    "IDWResult",
    "KNNResult",
    "Kriging",
    "KrigingDiagnostics",
    "KrigingResult",
    "LocationWise",
    "LocationWiseResult",
    "LossCalculation",
    "NormalScore",
    "ProfitCalculation",
    "SimulationReport",
]
