#  Copyright © 2026 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# AUTO-GENERATED BY `python -m evo.compute._stubgen generate`. DO NOT EDIT.
#
# Catalogue snapshot: GET /compute/orgs/{org_id}/tasks?details=true
# Captured: 2026-08-19
#
# The runtime is always live, so tasks published after the snapshot still run --
# they are simply not statically known until the snapshot is refreshed. Use
# `ComputeClient.arun(topic, task, parameters)`, or `SyncComputeClient.run(...)`,
# to reach them.

from typing import overload

from evo.common import IContext
from evo.common.interfaces import IFeedback

from .._facade_types import (
    _GeostatisticsBreakTiesHandle,
    _GeostatisticsConditionalTurningBandsHandle,
    _GeostatisticsConSimHandle,
    _GeostatisticsContinuousDistributionHandle,
    _GeostatisticsDeclusteringHandle,
    _GeostatisticsIDWHandle,
    _GeostatisticsKNNHandle,
    _GeostatisticsKrigingGcpHandle,
    _GeostatisticsKrigingHandle,
    _GeostatisticsLocationWiseHandle,
    _GeostatisticsLossCalculationHandle,
    _GeostatisticsNormalScoreGcpHandle,
    _GeostatisticsNormalScoreHandle,
    _GeostatisticsProfitCalculationHandle,
    _GeostatisticsSimulationReportHandle,
)
from .common import AllOfFilter as AllOfFilter
from .common import AnyOfFilter as AnyOfFilter
from .common import CreateAttribute as CreateAttribute
from .common import Ellipsoid as Ellipsoid
from .common import EllipsoidRanges as EllipsoidRanges
from .common import Filter as Filter
from .common import FilterCondition as FilterCondition
from .common import Rotation as Rotation
from .common import SearchNeighborhood as SearchNeighborhood
from .common import Source as Source
from .common import Target as Target
from .common import UpdateAttribute as UpdateAttribute
from .common.results import TaskResultList as TaskResultList
from .common.runner import TParams, TResult
from .geostatistics.break_ties import BreakTiesResult as BreakTiesResult
from .geostatistics.declustering import DeclusteringResult as DeclusteringResult
from .geostatistics.kriging import BlockDiscretisation as BlockDiscretisation
from .geostatistics.kriging import KrigingDiagnostics as KrigingDiagnostics
from .geostatistics.kriging import KrigingResult as KrigingResult
from .geostatistics.location_wise import LocationWiseResult as LocationWiseResult

@overload
async def run(
    context: IContext, parameters: TParams, *, preview: bool = ..., fb: IFeedback | None = ...
) -> TResult: ...
@overload
async def run(
    context: IContext, parameters: list[TParams], *, preview: bool = ..., fb: IFeedback | None = ...
) -> TaskResultList[TResult]: ...
async def run(
    context: IContext, parameters: TParams | list[TParams], *, preview: bool = False, fb: IFeedback | None = None
) -> TResult | TaskResultList[TResult]:
    """Run one or more compute tasks.

    Tasks are dispatched to the appropriate runner based on the parameter type.
    This allows running different task types together in a single call.

    Args:
        context: The context providing connector and org_id
        parameters: A single parameter object or list of parameters (can be mixed types)
        preview: If True, sets the ``API-Preview: opt-in`` header on requests.
            Required for tasks that are still in preview (e.g. kriging).
            Defaults to False.
        fb: Feedback interface for progress updates. If not provided, a default
            feedback is created via the registered feedback factory (see
            :func:`~evo.common.utils.set_feedback_factory`). Pass
            :data:`~evo.common.utils.NoFeedback` to explicitly suppress feedback.

    Returns:
        TaskResult for a single task, or TaskResults for multiple tasks

    Example (single task):
        >>> from evo.compute.tasks import run, SearchNeighborhood, Target
        >>> from evo.compute.tasks.geostatistics.kriging import KrigingParameters
        >>>
        >>> params = KrigingParameters(
        ...     source=pointset.attributes["grade"],
        ...     target=Target.new_attribute(block_model, "kriged_grade"),
        ...     variogram=variogram,
        ...     search=SearchNeighborhood(
        ...         ellipsoid=var_ell.scaled(2.0),
        ...         max_samples=20,
        ...     ),
        ... )
        >>> result = await run(manager, params, preview=True)

    Example (multiple tasks):
        >>> results = await run(manager, [
        ...     KrigingParameters(...),
        ...     KrigingParameters(...),
        ... ], preview=True)
        >>> results[0]  # Access first result"""
    ...

BreakTies: _GeostatisticsBreakTiesHandle
ConSim: _GeostatisticsConSimHandle
ConditionalTurningBands: _GeostatisticsConditionalTurningBandsHandle
ContinuousDistribution: _GeostatisticsContinuousDistributionHandle
Declustering: _GeostatisticsDeclusteringHandle
IDW: _GeostatisticsIDWHandle
KNN: _GeostatisticsKNNHandle
Kriging: _GeostatisticsKrigingHandle
KrigingGcp: _GeostatisticsKrigingGcpHandle
LocationWise: _GeostatisticsLocationWiseHandle
LossCalculation: _GeostatisticsLossCalculationHandle
NormalScore: _GeostatisticsNormalScoreHandle
NormalScoreGcp: _GeostatisticsNormalScoreGcpHandle
ProfitCalculation: _GeostatisticsProfitCalculationHandle
SimulationReport: _GeostatisticsSimulationReportHandle

__all__ = [
    "IDW",
    "KNN",
    "AllOfFilter",
    "AnyOfFilter",
    "BlockDiscretisation",
    "BreakTies",
    "BreakTiesResult",
    "ConSim",
    "ConditionalTurningBands",
    "ContinuousDistribution",
    "CreateAttribute",
    "Declustering",
    "DeclusteringResult",
    "Ellipsoid",
    "EllipsoidRanges",
    "Filter",
    "FilterCondition",
    "Kriging",
    "KrigingDiagnostics",
    "KrigingGcp",
    "KrigingResult",
    "LocationWise",
    "LocationWiseResult",
    "LossCalculation",
    "NormalScore",
    "NormalScoreGcp",
    "ProfitCalculation",
    "Rotation",
    "SearchNeighborhood",
    "SimulationReport",
    "Source",
    "Target",
    "TaskResultList",
    "UpdateAttribute",
    "run",
]
