#  Copyright © 2026 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# AUTO-GENERATED BY `python -m evo.compute._stubgen generate`. DO NOT EDIT.
#
# Catalogue snapshot: GET /compute/orgs/{org_id}/tasks?details=true
# Captured: 2026-08-19
#
# The runtime is always live, so tasks published after the snapshot still run --
# they are simply not statically known until the snapshot is refreshed. Use
# `ComputeClient.arun(topic, task, parameters)`, or `SyncComputeClient.run(...)`,
# to reach them.

from typing import Any, Literal, overload

from evo.common import IContext
from pydantic import BaseModel
from typing_extensions import NotRequired, TypedDict

from . import engine as _engine
from ._task_handles import TaskHandle
from .tasks.common import search as _search
from .tasks.common import source_target as _source_target

class _GeostatisticsBreakTiesHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsConSimHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsConditionalTurningBandsHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsContinuousDistributionHandle(TaskHandle[Any, Any]): ...

class _GeostatisticsDeclusteringParameters(TypedDict):
    source: _engine.DeclusteringSource | _engine.ObjectInput
    grid: _engine.DeclusteringGrid | _engine.ObjectInput
    target: _engine.DeclusteringTarget | _source_target.AnyTypedAttribute
    neighborhood: _engine.DeclusteringExtendedNeighborhood | _search.SearchNeighborhood
    power: NotRequired[float | None]

class _GeostatisticsDeclusteringHandle:
    """Computes grid-based declustering weights by measuring each sample's influence on evaluation locations. Supports both KNN (arithmetic mean) and IDW (inverse-distance weighted) modes via an optional power parameter."""
    @property
    def topic(self) -> str: ...
    @property
    def task(self) -> str: ...
    @overload
    def run(
        self,
        context: IContext,
        parameters: _GeostatisticsDeclusteringParameters | BaseModel,
        /,
        *,
        preview: bool | None = ...,
    ) -> _engine.SyncDeclusteringResult: ...
    @overload
    def run(
        self,
        context: IContext,
        /,
        *,
        source: _engine.DeclusteringSource | _engine.ObjectInput,
        grid: _engine.DeclusteringGrid | _engine.ObjectInput,
        target: _engine.DeclusteringTarget | _source_target.AnyTypedAttribute,
        neighborhood: _engine.DeclusteringExtendedNeighborhood | _search.SearchNeighborhood,
        power: float | None = ...,
        preview: bool | None = True,
    ) -> _engine.SyncDeclusteringResult: ...
    @overload
    async def arun(
        self,
        context: IContext,
        parameters: _GeostatisticsDeclusteringParameters | BaseModel,
        /,
        *,
        preview: bool | None = ...,
    ) -> _engine.DeclusteringResult: ...
    @overload
    async def arun(
        self,
        context: IContext,
        /,
        *,
        source: _engine.DeclusteringSource | _engine.ObjectInput,
        grid: _engine.DeclusteringGrid | _engine.ObjectInput,
        target: _engine.DeclusteringTarget | _source_target.AnyTypedAttribute,
        neighborhood: _engine.DeclusteringExtendedNeighborhood | _search.SearchNeighborhood,
        power: float | None = ...,
        preview: bool | None = True,
    ) -> _engine.DeclusteringResult: ...

class _GeostatisticsIDWHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsKNNHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsKrigingHandle(TaskHandle[Any, Any]): ...

class _GeostatisticsKrigingGcpParameters(TypedDict):
    source: _engine.KrigingGcpSource | _source_target.AnyTypedAttribute
    target: _engine.KrigingGcpTarget | _source_target.AnyTypedAttribute
    kriging_method: _engine.KrigingGcpSimpleKriging | _engine.KrigingGcpOrdinaryKriging
    variogram: _engine.ObjectInput
    neighborhood: _engine.KrigingGcpNeighborhoodWithOutlierRestrictions | _search.SearchNeighborhood
    block_discretisation: NotRequired[_engine.KrigingGcpBlockDiscretization | None]

class _GeostatisticsKrigingGcpHandle:
    """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/kriging'>guide</a>"""
    @property
    def topic(self) -> str: ...
    @property
    def task(self) -> str: ...
    @overload
    def run(
        self,
        context: IContext,
        parameters: _GeostatisticsKrigingGcpParameters | BaseModel,
        /,
        *,
        preview: bool | None = ...,
    ) -> _engine.SyncKrigingGcpResult: ...
    @overload
    def run(
        self,
        context: IContext,
        /,
        *,
        source: _engine.KrigingGcpSource | _source_target.AnyTypedAttribute,
        target: _engine.KrigingGcpTarget | _source_target.AnyTypedAttribute,
        kriging_method: _engine.KrigingGcpSimpleKriging | _engine.KrigingGcpOrdinaryKriging,
        variogram: _engine.ObjectInput,
        neighborhood: _engine.KrigingGcpNeighborhoodWithOutlierRestrictions | _search.SearchNeighborhood,
        block_discretisation: _engine.KrigingGcpBlockDiscretization | None = ...,
        preview: bool | None = True,
    ) -> _engine.SyncKrigingGcpResult: ...
    @overload
    async def arun(
        self,
        context: IContext,
        parameters: _GeostatisticsKrigingGcpParameters | BaseModel,
        /,
        *,
        preview: bool | None = ...,
    ) -> _engine.KrigingGcpResult: ...
    @overload
    async def arun(
        self,
        context: IContext,
        /,
        *,
        source: _engine.KrigingGcpSource | _source_target.AnyTypedAttribute,
        target: _engine.KrigingGcpTarget | _source_target.AnyTypedAttribute,
        kriging_method: _engine.KrigingGcpSimpleKriging | _engine.KrigingGcpOrdinaryKriging,
        variogram: _engine.ObjectInput,
        neighborhood: _engine.KrigingGcpNeighborhoodWithOutlierRestrictions | _search.SearchNeighborhood,
        block_discretisation: _engine.KrigingGcpBlockDiscretization | None = ...,
        preview: bool | None = True,
    ) -> _engine.KrigingGcpResult: ...

class _GeostatisticsLocationWiseHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsLossCalculationHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsNormalScoreHandle(TaskHandle[Any, Any]): ...

class _GeostatisticsNormalScoreGcpParameters(TypedDict):
    method: Literal["forward", "backward"]
    source: _engine.NormalScoreGcpSource | _source_target.AnyTypedAttribute
    distribution: _engine.ObjectInput
    target: _engine.NormalScoreGcpTarget | _source_target.AnyTypedAttribute

class _GeostatisticsNormalScoreGcpHandle:
    """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/normal-score'>guide</a>"""
    @property
    def topic(self) -> str: ...
    @property
    def task(self) -> str: ...
    @overload
    def run(
        self,
        context: IContext,
        parameters: _GeostatisticsNormalScoreGcpParameters | BaseModel,
        /,
        *,
        preview: bool | None = ...,
    ) -> _engine.SyncNormalScoreGcpResult: ...
    @overload
    def run(
        self,
        context: IContext,
        /,
        *,
        method: Literal["forward", "backward"],
        source: _engine.NormalScoreGcpSource | _source_target.AnyTypedAttribute,
        distribution: _engine.ObjectInput,
        target: _engine.NormalScoreGcpTarget | _source_target.AnyTypedAttribute,
        preview: bool | None = True,
    ) -> _engine.SyncNormalScoreGcpResult: ...
    @overload
    async def arun(
        self,
        context: IContext,
        parameters: _GeostatisticsNormalScoreGcpParameters | BaseModel,
        /,
        *,
        preview: bool | None = ...,
    ) -> _engine.NormalScoreGcpResult: ...
    @overload
    async def arun(
        self,
        context: IContext,
        /,
        *,
        method: Literal["forward", "backward"],
        source: _engine.NormalScoreGcpSource | _source_target.AnyTypedAttribute,
        distribution: _engine.ObjectInput,
        target: _engine.NormalScoreGcpTarget | _source_target.AnyTypedAttribute,
        preview: bool | None = True,
    ) -> _engine.NormalScoreGcpResult: ...

class _GeostatisticsProfitCalculationHandle(TaskHandle[Any, Any]): ...
class _GeostatisticsSimulationReportHandle(TaskHandle[Any, Any]): ...
