#  Copyright © 2026 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# AUTO-GENERATED BY `python -m evo.compute._stubgen generate`. DO NOT EDIT.
#
# Catalogue snapshot: GET /compute/orgs/{org_id}/tasks?details=true
# Captured: 2026-08-19
#
# The runtime is always live, so tasks published after the snapshot still run --
# they are simply not statically known until the snapshot is refreshed. Use
# `ComputeClient.arun(topic, task, parameters)` to reach them.

from typing import Any, Literal
from uuid import UUID

from evo.common import IContext
from evo.objects import ObjectMetadata, ObjectReference
from evo.objects.typed import BaseObject, DownloadedObject
from typing_extensions import NotRequired, TypedDict

from .outputs import ResultNode, TaskResult
from .overrides.geostatistics.kriging_gcp import KrigingGcpRunner as _GeostatisticsKrigingGcp
from .tasks.common.source_target import AnyTypedAttribute

__all__ = ["ComputeClient"]

ObjectInput = str | UUID | BaseObject | DownloadedObject | ObjectMetadata | ObjectReference
"""Any handle reference resolution can derive a geoscience object URL from."""

AttributeInput = str | AnyTypedAttribute
"""A typed attribute, a JMESPath expression, or a bare attribute name."""

class DeclusteringSource(TypedDict):
    """The source sample locations."""

    object: ObjectInput
    """Spatial locations of samples to compute declustering weights for."""

class DeclusteringGrid(TypedDict):
    """The evaluation grid for measuring sample influence."""

    object: ObjectInput
    """Regular grid or set of evaluation locations used to measure each sample's spatial influence."""

class DeclusteringTargetAttributeCreate(TypedDict):
    operation: Literal["create"]
    """The operation to perform on the attribute."""
    name: str
    """The name of the attribute to create."""

class DeclusteringTargetAttributeUpdate(TypedDict):
    operation: Literal["update"]
    """The operation to perform on the attribute."""
    reference: AttributeInput
    """Reference to an existing attribute to update."""

class DeclusteringTarget(TypedDict):
    """The target object and attribute to write declustering weights to."""

    object: ObjectInput
    """Object to write the declustering weight attribute onto. Typically the same object as the source."""
    attribute: DeclusteringTargetAttributeCreate | DeclusteringTargetAttributeUpdate | AttributeInput
    """Name of the attribute to create or update with the computed declustering weights."""

class DeclusteringNeighborhoodEllipsoidEllipsoidRanges(TypedDict):
    """The ranges of the ellipsoid"""

    major: float
    """The major axis length of the ellipsoid"""
    semi_major: float
    """The semi major axis length of the ellipsoid"""
    minor: float
    """The minor axis length of the ellipsoid"""

class DeclusteringRotation(TypedDict):
    """The rotation of the ellipsoid"""

    dip_azimuth: NotRequired[float]
    """first rotation, about the z-axis, in degrees"""
    dip: NotRequired[float]
    """second rotation, about the x-axis, in degrees"""
    pitch: NotRequired[float]
    """third rotation, about the z-axis, in degrees"""

class DeclusteringEllipsoid(TypedDict):
    """
    The ellipsoid, to search for points within
    Alias: anisotropy
    """

    ellipsoid_ranges: DeclusteringNeighborhoodEllipsoidEllipsoidRanges
    """The ranges of the ellipsoid"""
    rotation: DeclusteringRotation
    """The rotation of the ellipsoid"""

class DeclusteringExtendedNeighborhood(TypedDict):
    """Search neighborhood parameters. The search ellipsoid and sample limits control which samples influence each grid location during the estimation used to compute declustering weights."""

    ellipsoid: DeclusteringEllipsoid
    """
    The ellipsoid, to search for points within
    Alias: anisotropy
    """
    max_samples: int
    """
    The maximum number of samples to use for each evaluation point.
    Alias: max-samples
    """
    min_samples: NotRequired[int]
    """
    The minimum number of samples to use for each evaluation point.
    Alias: min-samples
    """
    max_empty_octants: NotRequired[int]
    """The maximum number of empty octants (aka sectors) allowed when searching for neighbors. Omitting this, or a value of 8, disables the octant check."""
    max_samples_per_octant: NotRequired[int | None]
    """The maximum number of samples to use from each octant."""
    max_samples_per_drillhole: NotRequired[int | None]
    """The maximum number of samples to use from each drillhole (defined by drillhole ID)"""
    max_empty_quadrants: NotRequired[int | None]
    """The maximum number of empty quadrants (2D sectors, ignoring Z) allowed when searching for neighbors. If not specified, quadrant filtering is disabled."""
    max_samples_per_quadrant: NotRequired[int | None]
    """The maximum number of samples to use from each quadrant (2D sectors, ignoring Z)."""
    max_drillholes_per_estimate: NotRequired[int | None]
    """The maximum number of drillholes to be used in each estimate."""

class DeclusteringResultAttribute(ResultNode):
    """Attribute containing the declustering weights."""

    reference: str
    """Reference to the attribute in the geoscience object."""
    name: str
    """The name of the output attribute."""

class DeclusteringResultTarget(ResultNode):
    """The target that was created or updated with declustering weights."""

    reference: str
    """Reference to a geoscience object."""
    name: str
    """The name of the geoscience object."""
    description: str | None
    """The description of the geoscience object."""
    schema_id: str
    """The ID of the Geoscience Object schema."""
    attribute: DeclusteringResultAttribute
    """Attribute containing the declustering weights."""

class DeclusteringResult(TaskResult):
    """Result of the declustering task."""

    message: str
    """A message that says what happened in the task."""
    target: DeclusteringResultTarget
    """The target that was created or updated with declustering weights."""

class NormalScoreGcpSource(TypedDict):
    """The source object and attribute containing the values to transform."""

    object: ObjectInput
    """Object containing the values to transform."""
    attribute: AttributeInput
    """The numeric attribute to apply the normal-score transformation to."""

class NormalScoreGcpTargetAttributeCreate(TypedDict):
    operation: Literal["create"]
    """The operation to perform on the attribute."""
    name: str
    """The name of the attribute to create."""

class NormalScoreGcpTargetAttributeUpdate(TypedDict):
    operation: Literal["update"]
    """The operation to perform on the attribute."""
    reference: AttributeInput
    """Reference to an existing attribute to update."""

class NormalScoreGcpTarget(TypedDict):
    """The target object and attribute to write the transformed values to."""

    object: ObjectInput
    """Object to write the transformed values to."""
    attribute: NormalScoreGcpTargetAttributeCreate | NormalScoreGcpTargetAttributeUpdate | AttributeInput
    """Name of the attribute to create or update on the target object."""

class NormalScoreGcpResultAttribute(ResultNode):
    """Attribute containing the transformed values."""

    reference: str
    """Reference to the attribute in the geoscience object."""
    name: str
    """The name of the output attribute."""

class NormalScoreGcpResultTarget(ResultNode):
    """The target object that was created or updated."""

    reference: str
    """Reference to a geoscience object."""
    name: str
    """The name of the geoscience object."""
    description: str | None
    """The description of the geoscience object."""
    schema_id: str
    """The ID of the Geoscience Object schema."""
    attribute: NormalScoreGcpResultAttribute
    """Attribute containing the transformed values."""

class NormalScoreGcpResult(TaskResult):
    """Result of the normal-score transformation task."""

    message: str
    """A message describing what happened in the task."""
    target: NormalScoreGcpResultTarget
    """The target object that was created or updated."""

class _GeostatisticsDeclustering:
    """Computes grid-based declustering weights by measuring each sample's influence on evaluation locations. Supports both KNN (arithmetic mean) and IDW (inverse-distance weighted) modes via an optional power parameter."""

    async def run(
        self,
        *,
        source: DeclusteringSource | ObjectInput,
        grid: DeclusteringGrid | ObjectInput,
        target: DeclusteringTarget | AnyTypedAttribute,
        neighborhood: DeclusteringExtendedNeighborhood,
        power: float | None = ...,
        preview: bool = True,
    ) -> DeclusteringResult:
        """Computes grid-based declustering weights by measuring each sample's influence on evaluation locations. Supports both KNN (arithmetic mean) and IDW (inverse-distance weighted) modes via an optional power parameter."""
        ...

class _GeostatisticsNormalScoreGcp:
    """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/normal-score'>guide</a>"""

    async def run(
        self,
        *,
        method: Literal["forward", "backward"],
        source: NormalScoreGcpSource | AnyTypedAttribute,
        distribution: ObjectInput,
        target: NormalScoreGcpTarget | AnyTypedAttribute,
        preview: bool = True,
    ) -> NormalScoreGcpResult:
        """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/normal-score'>guide</a>"""
        ...

class _GeostatisticsTasks:
    """Tasks published under the ``geostatistics`` topic."""

    declustering: _GeostatisticsDeclustering
    kriging_gcp: _GeostatisticsKrigingGcp
    normal_score_gcp: _GeostatisticsNormalScoreGcp

class ComputeClient:
    """
    Instance-bound async entry point to the compute task catalogue.

    The topic and task attributes below come from a point-in-time snapshot of the
    discovery catalogue. The runtime resolves them live, so a task missing from this
    stub still runs -- reach it with :meth:`arun`.
    """

    def __init__(
        self,
        context: IContext,
        *,
        cache_ttl_seconds: float = ...,
        validate: bool = ...,
        deep_validation: bool = ...,
        check_schemas: bool | None = ...,
    ) -> None: ...
    async def arun(
        self,
        topic: str,
        task: str,
        parameters: dict[str, Any],
        *,
        validate: bool | None = ...,
        deep_validation: bool | None = ...,
        check_schemas: bool | None = ...,
    ) -> TaskResult:
        """Run any task by name, including one this stub does not know about."""
        ...
    def __dir__(self) -> list[str]: ...
    def __repr__(self) -> str: ...
    geostatistics: _GeostatisticsTasks
