#  Copyright © 2026 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# AUTO-GENERATED BY `python -m evo.compute._stubgen generate`. DO NOT EDIT.
#
# Catalogue snapshot: GET /compute/orgs/{org_id}/tasks?details=true
# Captured: 2026-08-19
#
# The runtime is always live, so tasks published after the snapshot still run --
# they are simply not statically known until the snapshot is refreshed. Use
# `ComputeClient.arun(topic, task, parameters)` to reach them.

from typing import Any, Literal

from evo.common import IContext
from typing_extensions import NotRequired, TypedDict

__all__ = ["ComputeClient"]

class DeclusteringSource(TypedDict):
    """The source sample locations."""

    object: str
    """Spatial locations of samples to compute declustering weights for."""

class DeclusteringGrid(TypedDict):
    """The evaluation grid for measuring sample influence."""

    object: str
    """Regular grid or set of evaluation locations used to measure each sample's spatial influence."""

class DeclusteringTargetAttributeCreate(TypedDict):
    operation: Literal["create"]
    """The operation to perform on the attribute."""
    name: str
    """The name of the attribute to create."""

class DeclusteringTargetAttributeUpdate(TypedDict):
    operation: Literal["update"]
    """The operation to perform on the attribute."""
    reference: str
    """Reference to an existing attribute to update."""

class DeclusteringTarget(TypedDict):
    """The target object and attribute to write declustering weights to."""

    object: str
    """Object to write the declustering weight attribute onto. Typically the same object as the source."""
    attribute: DeclusteringTargetAttributeCreate | DeclusteringTargetAttributeUpdate
    """Name of the attribute to create or update with the computed declustering weights."""

class DeclusteringNeighborhoodEllipsoidEllipsoidRanges(TypedDict):
    """The ranges of the ellipsoid"""

    major: float
    """The major axis length of the ellipsoid"""
    semi_major: float
    """The semi major axis length of the ellipsoid"""
    minor: float
    """The minor axis length of the ellipsoid"""

class DeclusteringRotation(TypedDict):
    """The rotation of the ellipsoid"""

    dip_azimuth: NotRequired[float]
    """first rotation, about the z-axis, in degrees"""
    dip: NotRequired[float]
    """second rotation, about the x-axis, in degrees"""
    pitch: NotRequired[float]
    """third rotation, about the z-axis, in degrees"""

class DeclusteringEllipsoid(TypedDict):
    """
    The ellipsoid, to search for points within
    Alias: anisotropy
    """

    ellipsoid_ranges: DeclusteringNeighborhoodEllipsoidEllipsoidRanges
    """The ranges of the ellipsoid"""
    rotation: DeclusteringRotation
    """The rotation of the ellipsoid"""

class DeclusteringExtendedNeighborhood(TypedDict):
    """Search neighborhood parameters. The search ellipsoid and sample limits control which samples influence each grid location during the estimation used to compute declustering weights."""

    ellipsoid: DeclusteringEllipsoid
    """
    The ellipsoid, to search for points within
    Alias: anisotropy
    """
    max_samples: int
    """
    The maximum number of samples to use for each evaluation point.
    Alias: max-samples
    """
    min_samples: NotRequired[int]
    """
    The minimum number of samples to use for each evaluation point.
    Alias: min-samples
    """
    max_empty_octants: NotRequired[int]
    """The maximum number of empty octants (aka sectors) allowed when searching for neighbors. Omitting this, or a value of 8, disables the octant check."""
    max_samples_per_octant: NotRequired[int | None]
    """The maximum number of samples to use from each octant."""
    max_samples_per_drillhole: NotRequired[int | None]
    """The maximum number of samples to use from each drillhole (defined by drillhole ID)"""
    max_empty_quadrants: NotRequired[int | None]
    """The maximum number of empty quadrants (2D sectors, ignoring Z) allowed when searching for neighbors. If not specified, quadrant filtering is disabled."""
    max_samples_per_quadrant: NotRequired[int | None]
    """The maximum number of samples to use from each quadrant (2D sectors, ignoring Z)."""
    max_drillholes_per_estimate: NotRequired[int | None]
    """The maximum number of drillholes to be used in each estimate."""

class DeclusteringResultAttribute(TypedDict):
    """Attribute containing the declustering weights."""

    reference: str
    """Reference to the attribute in the geoscience object."""
    name: str
    """The name of the output attribute."""

class DeclusteringResultTarget(TypedDict):
    """The target that was created or updated with declustering weights."""

    reference: str
    """Reference to a geoscience object."""
    name: str
    """The name of the geoscience object."""
    description: str | None
    """The description of the geoscience object."""
    schema_id: str
    """The ID of the Geoscience Object schema."""
    attribute: DeclusteringResultAttribute
    """Attribute containing the declustering weights."""

class DeclusteringResult(TypedDict):
    """Result of the declustering task."""

    message: str
    """A message that says what happened in the task."""
    target: DeclusteringResultTarget
    """The target that was created or updated with declustering weights."""

class KrigingGcpSourceFilterCondition(TypedDict):
    """
    A leaf filter condition applied to one attribute of the filtered object.

    Exactly one operator field must be provided.

    - ``in``: Membership test. Provide string category names for
        ``CategoryAttribute`` objects or integers for integer-coded indices.
    - ``not_in``: Exclusion test.
    - ``equal``, ``not_equal``: Numeric equality/inequality.
    - ``greater_than``, ``greater_than_or_equal_to``, ``less_than``,
        ``less_than_or_equal_to``: Numeric comparisons on numeric attributes.
    """

    operator: Literal[
        "in",
        "not_in",
        "equal",
        "not_equal",
        "greater_than",
        "greater_than_or_equal_to",
        "less_than",
        "less_than_or_equal_to",
    ]
    """The filter operator. Use 'in' or 'not_in' for category/membership tests (pair with 'values'). Use 'equal', 'not_equal', 'greater_than', 'greater_than_or_equal_to', 'less_than', or 'less_than_or_equal_to' for numeric comparisons (pair with 'threshold')."""
    values: NotRequired[list[str] | None]
    """Category values to match. Required when operator is 'in' or 'not_in'. Use strings for string/category-name attributes; use integers for integer-coded attributes."""
    threshold: NotRequired[float | None]
    """Numeric threshold for comparison. Required when operator is 'equal', 'not_equal', 'greater_than', 'greater_than_or_equal_to', 'less_than', or 'less_than_or_equal_to'."""
    type: NotRequired[Literal["condition"]]
    """Identifies this as a leaf filter condition."""
    attribute: str
    """Attribute used to filter locations."""

class KrigingGcpSourceAnyOfFilter(TypedDict):
    """A composite filter that passes locations satisfying ANY child filter (OR logic)."""

    type: NotRequired[Literal["any_of"]]
    """Identifies this as an OR composite filter."""
    filters: list[KrigingGcpSourceFilterCondition | KrigingGcpSourceAllOfFilter | KrigingGcpSourceAnyOfFilter]
    """At least one of these filters must be satisfied (OR logic)."""

class KrigingGcpSourceAllOfFilter(TypedDict):
    """A composite filter that passes locations satisfying ALL child filters (AND logic)."""

    type: NotRequired[Literal["all_of"]]
    """Identifies this as an AND composite filter."""
    filters: list[KrigingGcpSourceFilterCondition | KrigingGcpSourceAllOfFilter | KrigingGcpSourceAnyOfFilter]
    """All of these filters must be satisfied (AND logic)."""

class KrigingGcpSourceFilter(TypedDict):
    """Optional filter to apply to the source object. This allows kriging to use only a subset of the known data, defined by filtering an attribute on the source object."""

    where: KrigingGcpSourceFilterCondition | KrigingGcpSourceAllOfFilter | KrigingGcpSourceAnyOfFilter
    """A filter expression defining which locations to include. Use a FilterCondition for a single predicate, AllOfFilter for AND logic, AnyOfFilter for OR logic, or nest them to build compound predicates."""

class KrigingGcpSource(TypedDict):
    """The source object and attribute containing known values."""

    object: str
    """Spatial locations of known values."""
    attribute: str
    """The known values, used to estimate values at unknown locations."""
    filter: NotRequired[KrigingGcpSourceFilter | None]
    """Optional filter to apply to the source object. This allows kriging to use only a subset of the known data, defined by filtering an attribute on the source object."""

class KrigingGcpTargetAttributeCreate(TypedDict):
    operation: Literal["create"]
    """The operation to perform on the attribute."""
    name: str
    """The name of the attribute to create."""

class KrigingGcpTargetAttributeUpdate(TypedDict):
    operation: Literal["update"]
    """The operation to perform on the attribute."""
    reference: str
    """Reference to an existing attribute to update."""

class KrigingGcpAnyOfFilter(TypedDict):
    """A composite filter that passes locations satisfying ANY child filter (OR logic)."""

    type: NotRequired[Literal["any_of"]]
    """Identifies this as an OR composite filter."""
    filters: list[KrigingGcpSourceFilterCondition | KrigingGcpAllOfFilter | KrigingGcpAnyOfFilter]
    """At least one of these filters must be satisfied (OR logic)."""

class KrigingGcpAllOfFilter(TypedDict):
    """A composite filter that passes locations satisfying ALL child filters (AND logic)."""

    type: NotRequired[Literal["all_of"]]
    """Identifies this as an AND composite filter."""
    filters: list[KrigingGcpSourceFilterCondition | KrigingGcpAllOfFilter | KrigingGcpAnyOfFilter]
    """All of these filters must be satisfied (AND logic)."""

class KrigingGcpFilter(TypedDict):
    """Optional filter to apply to the target object. This allows the kriging to only be applied to a subset of the target object, defined by filtering an attribute on the target object."""

    where: KrigingGcpSourceFilterCondition | KrigingGcpAllOfFilter | KrigingGcpAnyOfFilter
    """A filter expression defining which locations to include. Use a FilterCondition for a single predicate, AllOfFilter for AND logic, AnyOfFilter for OR logic, or nest them to build compound predicates."""

class KrigingGcpTarget(TypedDict):
    """The target object and attribute to create or update with kriging results."""

    object: str
    """Object to evaluate onto."""
    attribute: KrigingGcpTargetAttributeCreate | KrigingGcpTargetAttributeUpdate
    """Name of the attribute to create or update on the target object"""
    filter: NotRequired[KrigingGcpFilter | None]
    """Optional filter to apply to the target object. This allows the kriging to only be applied to a subset of the target object, defined by filtering an attribute on the target object."""

class KrigingGcpSimpleKriging(TypedDict):
    """Kriging method with a constant mean value."""

    type: Literal["simple"]
    """The type of kriging to use."""
    mean: float
    """The mean value, assumed to be constant across the domain."""

class KrigingGcpOrdinaryKriging(TypedDict):
    """Kriging method with a variable mean value."""

    type: Literal["ordinary"]
    """The type of kriging to use."""

class KrigingGcpNeighborhoodEllipsoidEllipsoidRanges(TypedDict):
    """The ranges of the ellipsoid"""

    major: float
    """The major axis length of the ellipsoid"""
    semi_major: float
    """The semi major axis length of the ellipsoid"""
    minor: float
    """The minor axis length of the ellipsoid"""

class KrigingGcpRotation(TypedDict):
    """The rotation of the ellipsoid"""

    dip_azimuth: NotRequired[float]
    """first rotation, about the z-axis, in degrees"""
    dip: NotRequired[float]
    """second rotation, about the x-axis, in degrees"""
    pitch: NotRequired[float]
    """third rotation, about the z-axis, in degrees"""

class KrigingGcpEllipsoid(TypedDict):
    """
    The ellipsoid, to search for points within
    Alias: anisotropy
    """

    ellipsoid_ranges: KrigingGcpNeighborhoodEllipsoidEllipsoidRanges
    """The ranges of the ellipsoid"""
    rotation: KrigingGcpRotation
    """The rotation of the ellipsoid"""

class KrigingGcpFractionalDistance(TypedDict):
    """Outlier distance specified as a fraction of the search radius."""

    type: Literal["fraction"]
    """Specify the distance as a fraction of the search radius."""
    distance: float
    """The distance to the outlier limit, as a fraction of the search radius (0.0 to 1.0). For example, a value of 0.5 means the outlier boundary is at 50% of the search radius."""

class KrigingGcpAbsoluteDistance(TypedDict):
    """Outlier distance specified as an absolute value."""

    type: Literal["absolute"]
    """Specify the distance as an absolute value."""
    distance: float
    """The absolute distance to the outlier limit. This cannot be used yet."""

class KrigingGcpOutlierRestriction(TypedDict):
    """Outlier restrictions."""

    action: Literal["clamp", "discard"]
    """The action to take on outliers. Clamp the value, or discard the point."""
    distance: KrigingGcpFractionalDistance | KrigingGcpAbsoluteDistance
    """The distance to the outlier limit."""
    max_value_threshold: NotRequired[float]
    """The maximum allowed value for the outlier limit. Values exceeding this threshold are either discarded or clamped."""
    clamp_delta: NotRequired[float]
    """The maximum randomly-applied delta value for clamped outlier values.Random delta values in the range [0.0...clamp_limit) are added to clamped values toavoid identical values occurring throughout the samples."""

class KrigingGcpNeighborhoodWithOutlierRestrictions(TypedDict):
    """In Kriging, the value of each evaluation point is determined by a set of nearby points with known values. The search parameters determines which nearby points to use."""

    ellipsoid: KrigingGcpEllipsoid
    """
    The ellipsoid, to search for points within
    Alias: anisotropy
    """
    max_samples: int
    """
    The maximum number of samples to use for each evaluation point.
    Alias: max-samples
    """
    min_samples: NotRequired[int]
    """
    The minimum number of samples to use for each evaluation point.
    Alias: min-samples
    """
    max_empty_octants: NotRequired[int]
    """The maximum number of empty octants (aka sectors) allowed when searching for neighbors. Omitting this, or a value of 8, disables the octant check."""
    max_samples_per_octant: NotRequired[int | None]
    """The maximum number of samples to use from each octant."""
    max_samples_per_drillhole: NotRequired[int | None]
    """The maximum number of samples to use from each drillhole (defined by drillhole ID)"""
    max_empty_quadrants: NotRequired[int | None]
    """The maximum number of empty quadrants (2D sectors, ignoring Z) allowed when searching for neighbors. If not specified, quadrant filtering is disabled."""
    max_samples_per_quadrant: NotRequired[int | None]
    """The maximum number of samples to use from each quadrant (2D sectors, ignoring Z)."""
    max_drillholes_per_estimate: NotRequired[int | None]
    """The maximum number of drillholes to be used in each estimate."""
    outliers: NotRequired[KrigingGcpOutlierRestriction | None]
    """Outlier restrictions."""

class KrigingGcpBlockDiscretization(TypedDict):
    """Sub-block discretization for block kriging. When provided, each target block is subdivided into nx * ny * nz sub-cells and the kriged value is averaged across these sub-cells. When omitted, point kriging is performed. Only applicable when the target is a 3D grid or block model."""

    nx: NotRequired[int]
    """Number of subdivisions in the x direction"""
    ny: NotRequired[int]
    """Number of subdivisions in the y direction"""
    nz: NotRequired[int]
    """Number of subdivisions in the z direction"""

class KrigingGcpResultAttribute(TypedDict):
    """Attribute containing the kriging result."""

    reference: str
    """Reference to the attribute in the geoscience object."""
    name: str
    """The name of the output attribute."""

class KrigingGcpResultTarget(TypedDict):
    """The target that was created or updated."""

    reference: str
    """Reference to a geoscience object."""
    name: str
    """The name of the geoscience object."""
    description: str | None
    """The description of the geoscience object."""
    schema_id: str
    """The ID of the Geoscience Object schema."""
    attribute: KrigingGcpResultAttribute
    """Attribute containing the kriging result."""

class KrigingGcpResult(TypedDict):
    """Result of the kriging task."""

    message: str
    """A message that says what happened in the task."""
    target: KrigingGcpResultTarget
    """The target that was created or updated."""

class NormalScoreGcpSource(TypedDict):
    """The source object and attribute containing the values to transform."""

    object: str
    """Object containing the values to transform."""
    attribute: str
    """The numeric attribute to apply the normal-score transformation to."""

class NormalScoreGcpTargetAttributeCreate(TypedDict):
    operation: Literal["create"]
    """The operation to perform on the attribute."""
    name: str
    """The name of the attribute to create."""

class NormalScoreGcpTargetAttributeUpdate(TypedDict):
    operation: Literal["update"]
    """The operation to perform on the attribute."""
    reference: str
    """Reference to an existing attribute to update."""

class NormalScoreGcpTarget(TypedDict):
    """The target object and attribute to write the transformed values to."""

    object: str
    """Object to write the transformed values to."""
    attribute: NormalScoreGcpTargetAttributeCreate | NormalScoreGcpTargetAttributeUpdate
    """Name of the attribute to create or update on the target object."""

class NormalScoreGcpResultAttribute(TypedDict):
    """Attribute containing the transformed values."""

    reference: str
    """Reference to the attribute in the geoscience object."""
    name: str
    """The name of the output attribute."""

class NormalScoreGcpResultTarget(TypedDict):
    """The target object that was created or updated."""

    reference: str
    """Reference to a geoscience object."""
    name: str
    """The name of the geoscience object."""
    description: str | None
    """The description of the geoscience object."""
    schema_id: str
    """The ID of the Geoscience Object schema."""
    attribute: NormalScoreGcpResultAttribute
    """Attribute containing the transformed values."""

class NormalScoreGcpResult(TypedDict):
    """Result of the normal-score transformation task."""

    message: str
    """A message describing what happened in the task."""
    target: NormalScoreGcpResultTarget
    """The target object that was created or updated."""

class _GeostatisticsDeclustering:
    """Computes grid-based declustering weights by measuring each sample's influence on evaluation locations. Supports both KNN (arithmetic mean) and IDW (inverse-distance weighted) modes via an optional power parameter."""

    async def run(
        self,
        *,
        source: DeclusteringSource,
        grid: DeclusteringGrid,
        target: DeclusteringTarget,
        neighborhood: DeclusteringExtendedNeighborhood,
        power: float | None = ...,
        preview: bool = True,
    ) -> DeclusteringResult:
        """Computes grid-based declustering weights by measuring each sample's influence on evaluation locations. Supports both KNN (arithmetic mean) and IDW (inverse-distance weighted) modes via an optional power parameter."""
        ...

class _GeostatisticsKrigingGcp:
    """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/kriging'>guide</a>"""

    async def run(
        self,
        *,
        source: KrigingGcpSource,
        target: KrigingGcpTarget,
        kriging_method: KrigingGcpSimpleKriging | KrigingGcpOrdinaryKriging,
        variogram: str,
        neighborhood: KrigingGcpNeighborhoodWithOutlierRestrictions,
        block_discretisation: KrigingGcpBlockDiscretization | None = ...,
        preview: bool = True,
    ) -> KrigingGcpResult:
        """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/kriging'>guide</a>"""
        ...

class _GeostatisticsNormalScoreGcp:
    """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/normal-score'>guide</a>"""

    async def run(
        self,
        *,
        method: Literal["forward", "backward"],
        source: NormalScoreGcpSource,
        distribution: str,
        target: NormalScoreGcpTarget,
        preview: bool = True,
    ) -> NormalScoreGcpResult:
        """For more information, please read the <a href='/docs/guides/geostatistics-tasks/tasks/normal-score'>guide</a>"""
        ...

class _GeostatisticsTasks:
    """Tasks published under the ``geostatistics`` topic."""

    declustering: _GeostatisticsDeclustering
    kriging_gcp: _GeostatisticsKrigingGcp
    normal_score_gcp: _GeostatisticsNormalScoreGcp

class ComputeClient:
    """
    Instance-bound async entry point to the compute task catalogue.

    The topic and task attributes below come from a point-in-time snapshot of the
    discovery catalogue. The runtime resolves them live, so a task missing from this
    stub still runs -- reach it with :meth:`arun`.
    """

    def __init__(
        self,
        context: IContext,
        *,
        cache_ttl_seconds: float = ...,
        validate: bool = ...,
        deep_validation: bool = ...,
    ) -> None: ...
    async def arun(
        self,
        topic: str,
        task: str,
        parameters: dict[str, Any],
        *,
        validate: bool | None = ...,
        deep_validation: bool | None = ...,
    ) -> dict[str, Any]:
        """Run any task by name, including one this stub does not know about."""
        ...
    def __dir__(self) -> list[str]: ...
    def __repr__(self) -> str: ...
    geostatistics: _GeostatisticsTasks
